k9s:
  cluster: datascience
  namespace:
    active: protostellar
    lockFavorites: true
    favorites:
      - peter-gaultney
      - protostellar
      - unified-directory
      - visits-api
      - thds
      - tim-blass
      - grant-andersen
      - ben-cornelis
      - matt-eby
  view:
    active: v1/pods protostellar
  featureGates:
    nodeShell: false
  proxy: null
